apiVersion: v1
kind: Service
metadata:
  name: question-app-service
spec:
  selector:
    app: question-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # corresponds to the containerPort in deplyoment configuration
